sources/OpenMcdf/CompoundFile.cs, sources/Test/OpenMcdf.Test/CompoundFileTest.cs
Adding APIs so that we can access data by storage/stream ID, GUID by storage/stream ID, number of directories, and type of storage/stream by ID.
=> Adding APIs for accessing data of Streams, GUID, storage type, and total number of directories

sources/OpenMcdf/CompoundFile.cs
=> Added cyclic sector chain check to CompoundFile.GetMiniSectorChain

.gitignore, OpenMcdf.sln, OpenMcdf.sln.DotSettings, sources/Test/OpenMcdf.Benchmark/InMemory.cs, sources/Test/OpenMcdf.Benchmark/OpenMcdf.Benchmark.csproj, sources/Test/OpenMcdf.Benchmark/Program.cs
Part of performance investigation for  ironfede/openmcdf/#44
=> Benchmarking stream reading

sources/OpenMcdf/StreamView.cs, sources/Test/OpenMcdf.Extensions.Test/CFSStreamExtensionsTest.cs, sources/Test/OpenMcdf.Test/CFSStreamTest.cs
The fix for this issue consists of an improved handling of the lenght property in the StreamView class.
=> Added unit test method to demonstrate issue #88 and provided a fix.

sources/OpenMcdf/CFStorage.cs, sources/Test/OpenMcdf.Test/CompoundFileTest.cs
Hi there,
please accept the unit test and implementation fix for #90 .
Thank you!
=> Fix for issue #90

sources/OpenMcdf/CompoundFile.cs
- There are issues with certain constructors that not all configuration options are set properly. This is now consolidated to one function
- Constructors also refer to each other when possible to not duplicate too much code
=> Fix constructors with configuration

sources/OpenMcdf/CompoundFile.cs
- No need to validate if validation is disabled
- Combine Contains/Add with using the result of Add
=> Improve unique sector index validation

sources/OpenMcdf/CompoundFile.cs
Just as the title says - my Visual Studio is suggesting these changes.
=> A few spelling suggestions made by the Visual Studio spell checker

sources/OpenMcdf.Extensions/OLEProperties/Common.cs, sources/OpenMcdf.Extensions/OLEProperties/DictionaryEntry.cs, sources/OpenMcdf.Extensions/OLEProperties/DictionaryProperty.cs, sources/OpenMcdf.Extensions/OLEProperties/OLEPropertiesContainer.cs, sources/OpenMcdf.Extensions/OLEProperties/OLEProperty.cs, sources/OpenMcdf.Extensions/OLEProperties/PropertyFactory.cs, sources/OpenMcdf.Extensions/OLEProperties/TypedPropertyValue.cs, sources/OpenMcdf.Extensions/StreamDecorator.cs, sources/OpenMcdf/CFItem.cs, sources/OpenMcdf/CFStorage.cs, sources/OpenMcdf/CFStream.cs, sources/OpenMcdf/CompoundFile.cs, sources/OpenMcdf/DirectoryEntry.cs, sources/OpenMcdf/Header.cs, sources/OpenMcdf/RBTree/RBTree.cs, sources/OpenMcdf/Sector.cs, sources/OpenMcdf/SectorCollection.cs, sources/OpenMcdf/StreamView.cs, sources/Structured Storage Explorer/MainForm.cs, sources/Structured Storage Explorer/StreamDataProvider.cs, sources/Test/OpenMcdf.Extensions.Test/CFSStreamExtensionsTest.cs, sources/Test/OpenMcdf.MemTest/Program.cs, sources/Test/OpenMcdf.PerfTest/Program.cs, sources/Test/OpenMcdf.Test/CFSStreamTest.cs, sources/Test/OpenMcdf.Test/CFSTorageTest.cs, sources/Test/OpenMcdf.Test/CompoundFileTest.cs, sources/Test/OpenMcdf.Test/RBTreeTest.cs, sources/Test/OpenMcdf.Test/StreamRWTest.cs
Getting close towards the end of the formatting changes I'd like to get in before making more functional changes.
The last significant one would be to use auto properties, which simplifies the code quite a bit, but the auto-fix drops some comments (and creates some ambiguity since `_disposed` is used for `Closed` is some situations), so these ones are less contentious.
=> IDE analyzer fixes

sources/OpenMcdf.Extensions/OLEProperties/PropertySetStream.cs, sources/OpenMcdf/CFStorage.cs, sources/OpenMcdf/CompoundFile.cs, sources/OpenMcdf/Header.cs, sources/Structured Storage Explorer/MainForm.cs, sources/Test/OpenMcdf.Test/CFSStreamTest.cs, sources/Test/OpenMcdf.Test/CFSTorageTest.cs, sources/Test/OpenMcdf.Test/CompoundFileTest.cs
A collection of performance improvements, mostly to silence perf-related analyzer warnings
=> Initial performance improvements

.editorconfig, sources/OpenMcdf.Extensions/OLEProperties/Interfaces/IDictionaryProperty.cs, sources/OpenMcdf/CompoundFile.cs, sources/Structured Storage Explorer/MainForm.cs, sources/Structured Storage Explorer/StreamDataProvider.cs, sources/Test/OpenMcdf.Extensions.Test/CFSStreamExtensionsTest.cs, sources/Test/OpenMcdf.Extensions.Test/OLEPropertiesExtensionsTest.cs, sources/Test/OpenMcdf.MemTest/Program.cs, sources/Test/OpenMcdf.PerfTest/Program.cs, sources/Test/OpenMcdf.Test/CFSStreamTest.cs, sources/Test/OpenMcdf.Test/CFSTorageTest.cs, sources/Test/OpenMcdf.Test/CompoundFileTest.cs
Fixes warnings or otherwise reduces their severity to suggestions
=> Fix build warnings

sources/OpenMcdf.Extensions/OLEProperties/DictionaryEntry.cs, sources/OpenMcdf.Extensions/OLEProperties/DictionaryProperty.cs, sources/OpenMcdf.Extensions/OLEProperties/OLEPropertiesContainer.cs, sources/OpenMcdf.Extensions/OLEProperties/OLEProperty.cs, sources/OpenMcdf.Extensions/OLEProperties/PropertyFactory.cs, sources/OpenMcdf.Extensions/OLEProperties/PropertySetStream.cs, sources/OpenMcdf.Extensions/OLEProperties/TypedPropertyValue.cs, sources/OpenMcdf.Extensions/StreamDecorator.cs, sources/OpenMcdf/CFItem.cs, sources/OpenMcdf/CFStorage.cs, sources/OpenMcdf/CFStream.cs, sources/OpenMcdf/CompoundFile.cs, sources/OpenMcdf/DirectoryEntry.cs, sources/OpenMcdf/Header.cs, sources/OpenMcdf/RBTree/RBTree.cs, sources/OpenMcdf/Sector.cs, sources/OpenMcdf/SectorCollection.cs, sources/OpenMcdf/StreamRW.cs, sources/OpenMcdf/StreamView.cs, sources/Structured Storage Explorer/MainForm.cs, sources/Structured Storage Explorer/PreferencesForm.cs, sources/Structured Storage Explorer/StreamDataProvider.cs, sources/Test/OpenMcdf.Benchmark/Extensions.cs, sources/Test/OpenMcdf.Extensions.Test/OLEPropertiesExtensionsTest.cs, sources/Test/OpenMcdf.Test/CFSTorageTest.cs, sources/Test/OpenMcdf.Test/CompoundFileTest.cs, sources/Test/OpenMcdf.Test/RBTreeTest.cs, sources/Test/OpenMcdf.Test/StreamRWTest.cs
Another round of style updates mostly non-contentious, automated style updates after enabling C#10
=> C#10 style updates

sources/OpenMcdf/CompoundFile.cs, sources/OpenMcdf/DirectoryEntry.cs, sources/OpenMcdf/Header.cs, sources/OpenMcdf/RBTree/RBTree.cs, sources/OpenMcdf/Sector.cs, sources/OpenMcdf/StreamRW.cs, sources/OpenMcdf/StreamView.cs, sources/Test/OpenMcdf.PerfTest/Program.cs
A first round of memory usage improvements for v2 (further improvements conflict with other open PRs)
=> Memory usage improvements

exclusion.dic, sources/OpenMcdf.Extensions/OLEProperties/OLEProperty.cs, sources/OpenMcdf.Extensions/OLEProperties/PropertyFactory.cs, sources/OpenMcdf/CFStorage.cs, sources/OpenMcdf/CompoundFile.cs, sources/OpenMcdf/DirectoryEntry.cs, sources/OpenMcdf/Header.cs, sources/OpenMcdf/IDirectoryEntry.cs, sources/OpenMcdf/SectorCollection.cs, sources/OpenMcdf/StreamView.cs
An initial round of maintainability improvements that don't alter the public API
=> Initial maintainability improvements

sources/OpenMcdf/CFStream.cs, sources/OpenMcdf/CompoundFile.cs, sources/OpenMcdf/Sector.cs
Mostly addresses analyzer warnings for CA2000 (Dispose objects before losing scope) in the core projects
=> Initial reliability fixes

sources/OpenMcdf/BinaryPrimitives.cs, sources/OpenMcdf/CompoundFile.cs, sources/OpenMcdf/Sector.cs, sources/OpenMcdf/StreamView.cs, sources/Test/OpenMcdf.MemTest/Program.cs
Plus some BinaryPrimitives equivalent to reduce memory allocations for block copies
=> Use StreamRW to reduce memory allocations

sources/OpenMcdf/SectorCollection.cs
Some performance improvements and nit-pick fixes for SectorCollection
=> Refactor SectorCollection

sources/OpenMcdf/CFStorage.cs, sources/OpenMcdf/RBTree/IRBNode.cs, sources/OpenMcdf/RBTree/RBTree.cs, sources/OpenMcdf/RBTree/RBTreeEnumerator.cs
Some cleanup fpr v2.4 in preparation for v3:
- Remove duplicated code
- Remove unused code
- Move types to their own files
- Simplify tracing
=> Refactor RBTree

sources/OpenMcdf.Extensions/OLEProperties/OLEPropertiesContainer.cs, sources/OpenMcdf.Extensions/OLEProperties/OLEProperty.cs, sources/Test/OpenMcdf.Extensions.Test/CFSStreamExtensionsTest.cs, sources/Test/OpenMcdf.Extensions.Test/Helpers.cs, sources/Test/OpenMcdf.Extensions.Test/OLEPropertiesExtensionsTest.cs
Clean-up and refactor extensions tests in preparation for adding some new tests that are currently failing against v2.3
=> Refactor extension tests

sources/OpenMcdf.Extensions/StreamDecorator.cs, sources/Test/OpenMcdf.Extensions.Test/CFSStreamExtensionsTest.cs, sources/Test/OpenMcdf.Test/CFStreamTest.cs
=> Truncate StreamDecorator reads

sources/OpenMcdf.Extensions/OLEProperties/DictionaryProperty.cs, sources/OpenMcdf.Extensions/OLEProperties/OLEPropertiesContainer.cs, sources/OpenMcdf.Extensions/OLEProperties/TypedPropertyValue.cs
=> Make a few private functions static

sources/OpenMcdf/CFStream.cs, sources/OpenMcdf/CompoundFile.cs, sources/OpenMcdf/Sector.cs, sources/OpenMcdf/StreamExtensions.cs, sources/OpenMcdf/StreamRW.cs
=> Avoid inexact stream reads (CA2022)

OpenMcdf.Tests/StreamTests.cs, OpenMcdf/Fat.cs, OpenMcdf/FatChainEnumerator.cs
=> Fix extending FAT for DirectoryEntries

.github/workflows/dotnet-desktop.yml, OpenMcdf.Ole.Tests/OpenMcdf.Ole.Tests.csproj, OpenMcdf.Tests/OpenMcdf.Tests.csproj
As https://github.com/ironfede/openmcdf/pull/179 but for v3
=> Readd GithubActionsTestLogger to the CI builds

OpenMcdf.Tests/RootStorageTests.cs, OpenMcdf/RootStorage.cs
=> Add SwitchTo filename overload

OpenMcdf.Ole/ITypedPropertyValue.cs
Another small thing where all the usages are internal now
=> Make PropertyDimensions internal

StructuredStorageExplorer/MainForm.Designer.cs
Just a thought when I was using it to look at some .msg files at work earlier
=> Add *.msg files to the file type filter in structured storage explorer

OpenMcdf/FatChainEnumerator.cs
Improves read performance for long FAT chains
Fixes: #282
=> Use Brent's cycle detection algorithm

OpenMcdf.Tests/RootStorageTests.cs, OpenMcdf.Tests/StorageTests.cs, OpenMcdf/Storage.cs, exclusion.dic
=> Fix CLSID typo

OpenMcdf.Tests/BinaryReaderTests.cs, OpenMcdf.Tests/BinaryWriterTests.cs, OpenMcdf.Tests/EntryInfoTests.cs, OpenMcdf.Tests/StorageTests.cs, OpenMcdf/CfbBinaryReader.cs, OpenMcdf/DirectoryEntry.cs, OpenMcdf/FileTime.cs, OpenMcdf/Storage.cs
=> Throw FileFormatException for invalid DateTimes

OpenMcdf/CfbStream.cs, OpenMcdf/RootStorage.cs, OpenMcdf/Storage.cs
=> Add public API documentation

StructuredStorageExplorer/MainForm.Designer.cs, StructuredStorageExplorer/MainForm.cs, StructuredStorageExplorer/MainForm.resx, StructuredStorageExplorer/NodeSelection.cs, StructuredStorageExplorer/PreferencesForm.Designer.cs, StructuredStorageExplorer/PreferencesForm.resx, StructuredStorageExplorer/StructuredStorageExplorer.csproj, StructuredStorageExplorer/Utils.cs, StructuredStorageExplorer/app.manifest
Various improvements and fixes for Stuctured Storage Explorer
=> Update Storage Explorer

OpenMcdf.Tests/DebugWriter.cs, OpenMcdf/DirectoryTree.cs, OpenMcdf/Storage.cs
=> Fix DirectoryEntry removal

OpenMcdf.Tests/BinaryWriterTests.cs, OpenMcdf/CfbBinaryWriter.cs, OpenMcdf/DirectoryEntries.cs, OpenMcdf/DirectoryTree.cs, OpenMcdf/Fat.cs, OpenMcdf/MiniFat.cs, OpenMcdf/RootContext.cs, OpenMcdf/RootStorage.cs
=> Validate red-black tree violations
