ironfede/openmcdf

sources/OpenMcdf/CompoundFile.cs

When releasing memory it can crash when the sector is null

Fixes crash when sector is null

---

sources/OpenMcdf.Extensions/OpenMcdf.Extensions.csproj
sources/OpenMcdf/OpenMcdf.csproj

* Closing issue #24 
Tests are still green 
The following is a trace of the results on my local machine:
Successfully created package 'XXX\Projects\openmcdf\bin\Debug\OpenMcdf\OpenMcdf.1.0.0.nupkg'.
Successfully created package 'XXX\Projects\openmcdf\bin\Debug\OpenMcdf\OpenMcdf.1.0.0.symbols.nupkg'.
Successfully created package 'XXX\Projects\openmcdf\bin\Debug\OpenMcdf.Extensions\OpenMcdf.Extensions.1.0.0.nupkg'.
Successfully created package 'XXX\Projects\openmcdf\bin\Debug\OpenMcdf.Extensions\OpenMcdf.Extensions.1.0.0.symbols.nupkg'.

closes ironfede/openmcdf#24

---

sources/OpenMcdf/CompoundFile.cs

some of the constructors of CompoundFile that took in a config were not setting the config field. this led to an issue where if the LeaveOpen flag was set, calling Close() would still close the stream.

saving config in constructors

---

.gitignore
azure-pipelines.yml

* This PR is part of the work on the issue  #44. The goal is to have continuous integration and to run the build and tests on every commit.
* I choose Azure pipelines since they are free and I find their integration with Github superior to other alternatives
* [This web page](https://dev.azure.com/michaelpavlovsky/michaelpavlovsky/_build/results?buildId=15&view=ms.vss-test-web.build-test-results-tab) demonstrates the integration enabled and running on my fork of this repository
* Please notice that I deliberately run the tests only using dotnet core and inside Linux
* My intention is to have Continuous integration available prior to my next pull request
* @ironfede  please turn on the integration with azure pipelines on this repository. This PR has the necessary configuration files and if …

Continious integration using Azure Pipe Lines

---

sources/OpenMcdf/CompoundFile.cs
sources/OpenMcdf/DirectoryEntry.cs

See the below quote from the specification:
> Free (unused) directory entries are marked with Object Type 0x0 (unknown or unallocated). **The entire directory entry must consist of all zeroes** except for the child, right sibling, and left sibling pointers, which must be initialized to NOSTREAM (0xFFFFFFFF).
This function:
https://github.com/ironfede/openmcdf/blob/c9d74e2a21cc047d8962032449428fb6ecc45ca4/sources/OpenMcdf/CompoundFile.cs#L1626
Did not reset all required parts it needs to.
Likewise, this:
https://github.com/ironfede/openmcdf/blob/c9d74e2a21cc047d8962032449428fb6ecc45ca4/sources/OpenMcdf/CompoundFile.cs#L2534
was not specifiaction compliant either.

Fix so unallocated directory entries are now spec compliant

---

sources/OpenMcdf.Extensions/OLEProperties/TypedPropertyValue.cs

- E.g. If the start position is 0 and the end position is 13, then `size = 13-0=13`, `m = (int)size % 4=1`, so we don't need `m` bytes of padding, but actually `4`

Fix padding reading in TypedPropertyValue

---

sources/OpenMcdf.Extensions/OLEProperties/OLEPropertiesContainer.cs

refs #47 
I tried doing a test with adding a user defined property to a documentand got an ArgumentOutOfRange exception:
```
List`1.get_Item(Int32 index)
PropertySetStream.Write(BinaryWriter bw) line 218
OLEPropertiesContainer.Save(CFStream cfStream) line 264
```
which looks to be because it sets the number of properties to ```this.UserDefinedProperties.Properties.Count()``` but then populates the data with ```this.properties```.
The overall write alas still doesn't seem to work, but this particular exception goes away

Fix out-of-range exception in OLEPropertiesContainer.Save

---

sources/OpenMcdf.Extensions/OLEProperties/PropertyFactory.cs
sources/Test/OpenMcdf.Extensions.Test/OLEPropertiesExtensionsTest.cs

refs #47 
When testing adding or modifying properties, I noticed that new or modified string properties weren't getting null terminated, and that was causing issues with office apps like powerpoint which were showing truncated property values.
I went to add the null values, but it isn't quite that simple as any properties that OpenMxdf has read itself will retain the null terminators from the originating file whereas new values supplied by a user generally won't, so - try to check if the value has a trailing null already and only write an extra one if not.
This *seems* to work, though i'm not 100% sure on the situation with empty strings (The Windows native compound doc apis seem to set a length of 1 and include a null for empty string properties, so I've done the same)

Ensure string values are null terminated when writing them

---

sources/OpenMcdf.Extensions/OLEProperties/Common.cs
sources/OpenMcdf.Extensions/OLEProperties/DictionaryEntry.cs
sources/OpenMcdf.Extensions/OLEProperties/DictionaryProperty.cs

According to the Microsoft documentation at https://learn.microsoft.com/en-us/openspecs/windows_protocols/MS-OLEPS/99127b7f-c440-4697-91a4-c853086d6b33 : 
1) The dictinoary entry should be 
Number of entries
entries
padding so the size is a multiple of 4 bytes
and the current code doesn't do the padding.
2) Each dictionary entry should be
Identifier
Length
Name
but the current code only writes the Identifier and Name, not the length.
Also, if the codepage is CP_WINUNICODE then each individual string entry should be passed as well.

Rework the writing of DictionaryProperty

---

sources/OpenMcdf.Extensions/OLEProperties/PropertySetStream.cs

As per the Microsoft documentation at https://learn.microsoft.com/en-us/openspecs/office_file_formats/ms-oshared/fe59ffd9-79e9-44fb-a1c9-2466057b05c6 - 
```
The total size of this property set’s PropertySet structure ([MS-OLEPS] section [2.20](https://learn.microsoft.com/en-us/openspecs/windows_protocols/MS-OLEPS/aefcbddf-f299-4f5e-a9da-65ce4ca55075)) MUST be padded to a multiple of 4 bytes
```
but the padding code was commented out?
When debugging an attempt at writing the user defined properties, I had a case where the size ended up at 299 bytes when it should really be padded up to 300, and I think this fixes that.
@@NOTE@@ It might need additional padding adding to the end of the user defined section, but the documents I'm testing with are all ending up with the size a multiple of 4 …

Tweak the writing of offsets when writing user defined properties

---

sources/Test/OpenMcdf.Benchmark/Extensions.cs
sources/Test/OpenMcdf.Benchmark/OpenMcdf.Benchmark.csproj
sources/Test/OpenMcdf.Benchmark/Program.cs

I just thought it'd be useful to test a few more things whilst looking at other issues, e.g.
```
| Method                             | Mean      | Error    | StdDev   | Gen0    | Gen1   | Allocated |
|----------------------------------- |----------:|---------:|---------:|--------:|-------:|----------:|
| TestReadSummaryInformation         |  71.00 us | 0.761 us | 0.675 us | 18.1885 | 0.2441 | 112.02 KB |
| TestReadDocumentSummaryInformation | 126.58 us | 2.374 us | 4.401 us | 33.9355 | 0.4883 | 209.02 KB |
```

Add a couple of benchmarks for AsOLEPropertiesContainer

---

sources/OpenMcdf.Extensions/OLEProperties/OLEPropertiesContainer.cs
sources/Test/OpenMcdf.Extensions.Test/OLEPropertiesExtensionsTest.cs

refs #104 and https://github.com/ironfede/openmcdf/pull/106#issuecomment-1963066508

Always populate UserDefinedProperties.PropertyNames when reading a file with UserDefined properties, and add a read/write user property test

---

sources/OpenMcdf.Extensions/StreamDecorator.cs

Hopefully a trivial change, but - there a quite a few build warnings about public functions not having doc comments, e.g.
So I just added some to fix one batch of the complaints (though most of the functions are just inherited from System.IO.Stream anyway)

Add doc comments to StreamDecorator

---

sources/OpenMcdf.Extensions/OLEProperties/ProperyIdentifiers.cs

I don't think there should be a need to allocate a new dictionary on every call here?
Also - use Dictionary.TryGetValue rather than ContainsKey/Indexer - 
refs https://learn.microsoft.com/en-gb/dotnet/fundamentals/code-analysis/quality-rules/ca1854

Rework OLEProperties.GetDescription to avoid allocating temporary dictionaries

---

sources/Test/OpenMcdf.Extensions.Test/OpenMcdf.Extensions.Test.csproj
sources/Test/OpenMcdf.Test/OpenMcdf.Test.csproj

Visual Studio was giving me some warnings about transitive references to test packages with known CVEs, and updating the test SDK to 17.3.3 seems to fix that as it removes a great many old dependencies:
```
Test\OpenMcdf.Test
Uninstalling:
Microsoft.CSharp.4.3.0
Microsoft.Win32.Primitives.4.3.0
NETStandard.Library.1.6.1
runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.0
runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.0
runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.0
runtime.native.System.IO.Compression.4.3.0
runtime.native.System.Net.Http.4.3.0
runtime.native.System.Security.Cryptography.Apple.4.3.0
runtime.native.System.Security.Cryptography.OpenSsl.4.3.0 …
```

Update Microsoft.NET.Test.Sdk to 17.3.3

---

sources/Test/OpenMcdf.Benchmark/InMemory.cs

Just fixes this deprecation warning in the build:

Use SimpleJob instead of CoreJob in the 'InMemory' benchmark

---

sources/OpenMcdf/OpenMcdf.csproj
sources/Structured Storage Explorer/StructuredStorageExplorer.csproj
sources/Test/OpenMcdf.Benchmark/OpenMcdf.Benchmark.csproj
sources/Test/OpenMcdf.MemTest/OpenMcdf.MemTest.csproj
sources/Test/OpenMcdf.PerfTest/OpenMcdf.PerfTest.csproj

This just fixes the warnings in the IDE, then does the minimal amount of work required to convert the StructuredStorageExplorer, MemTest and PerfTest to an SDK-style projects via the .NET Upgrade Assistant.
I'm afraid I can't really judge whether additional changes would be required/desired in order to want to merge it.
e.g. Maybe you would prefer `net45` over `net48` for consistency with other targets?
This is intended to pave the way for adding Directory.Build.props/targets to allow for common build configuration to be set across the solution.

Convert to SDK-style projects

---

sources/Test/OpenMcdf.Benchmark/Extensions.cs
sources/Test/OpenMcdf.Benchmark/InMemory.cs
sources/Test/OpenMcdf.Benchmark/OpenMcdf.Benchmark.csproj

netcoreapp3.1 is obsolete and unsupported
Even net6.0 will be EOL towards the end of the year...
https://learn.microsoft.com/en-us/lifecycle/products/microsoft-net-and-net-core

Target net6.0 for OpenMcdf.Benchmark

---

sources/OpenMcdf.Extensions/OLEProperties/DictionaryEntry.cs
sources/OpenMcdf.Extensions/OLEProperties/DictionaryProperty.cs
sources/OpenMcdf.Extensions/OLEProperties/OLEPropertiesContainer.cs
sources/OpenMcdf.Extensions/OLEProperties/OLEProperty.cs
sources/OpenMcdf.Extensions/OLEProperties/PropertyFactory.cs
sources/OpenMcdf.Extensions/OLEProperties/PropertySet.cs
sources/OpenMcdf.Extensions/OLEProperties/TypedPropertyValue.cs
sources/OpenMcdf.Extensions/StreamDecorator.cs
sources/OpenMcdf/CFItem.cs
sources/OpenMcdf/CFStorage.cs
sources/OpenMcdf/CompoundFile.cs
sources/OpenMcdf/DirectoryEntry.cs
sources/OpenMcdf/Header.cs
sources/OpenMcdf/RBTree/RBTree.cs
sources/OpenMcdf/Sector.cs
sources/OpenMcdf/SectorCollection.cs
sources/OpenMcdf/StreamRW.cs
sources/OpenMcdf/StreamView.cs
sources/Structured Storage Explorer/MainForm.cs
sources/Structured Storage Explorer/StreamDataProvider.cs
sources/Test/OpenMcdf.Extensions.Test/CFSStreamExtensionsTest.cs
sources/Test/OpenMcdf.Extensions.Test/OLEPropertiesExtensionsTest.cs
sources/Test/OpenMcdf.PerfTest/Program.cs
sources/Test/OpenMcdf.Test/CFSStreamTest.cs
sources/Test/OpenMcdf.Test/CFSTorageTest.cs
sources/Test/OpenMcdf.Test/CompoundFileTest.cs
sources/Test/OpenMcdf.Test/RBTreeTest.cs
sources/Test/OpenMcdf.Test/SectorCollectionTest.cs

These are the last set of analyzer fixes that are reasonable to apply without increasing the C# language version.
From this point, I could start digging into some bug fixes for the 2.x branch more effectively, but it might also be nice to enable C# 10 and do one more round of fixes to gain even better alignment between 2.x and 3.x.

Analyzer fixes

---

sources/OpenMcdf.Extensions/OLEProperties/PropertyFactory.cs
sources/OpenMcdf/CFItem.cs
sources/OpenMcdf/DirectoryEntry.cs
sources/Test/OpenMcdf.Extensions.Test/OLEPropertiesExtensionsTest.cs
sources/Test/OpenMcdf.MemTest/Program.cs
sources/Test/OpenMcdf.PerfTest/Program.cs

Fixes #161 by returning DateTimes as UTC
Also uses a monotonic clock for performance measurements.

Deserialize DateTimes as UTC

---

sources/OpenMcdf/CFStorage.cs
sources/OpenMcdf/CompoundFile.cs
sources/OpenMcdf/DirectoryEntry.cs
sources/OpenMcdf/IDirectoryEntry.cs
sources/OpenMcdf/RBTree/RBTree.cs

Adds the following methods:
- CompoundFile.Dispose (as public)
- ContainsStream
- ContainsStorage
- TryDelete
While adding them, I found some problems with the existing implementation that I have fixed since it made sense to do so at the same time:
- RBTreeEnumerator performed multiple enumeration on a Queue via LINQ, but RBTree did not support LINQ (IEnumerable<T>)
- Directory resets invloved multiple redundant casts and lookups

2.4 API additions

---

sources/Test/OpenMcdf.Extensions.Test/OLEPropertiesExtensionsTest.cs
sources/Test/OpenMcdf.Test/CFStorageTest.cs
sources/Test/OpenMcdf.Test/CFStreamTest.cs
sources/Test/OpenMcdf.Test/CompoundFileTest.cs
sources/Test/OpenMcdf.Test/RBTreeTest.cs

The counterpart to fixing CA2000 in the core library, this fixes some more test implementation logic (e.g. more Assert.ThrowsException, etc.), removes redundant code, and fixes CA2000 for the tests

Fix object disposal in tests

---

sources/OpenMcdf.Extensions/OLEProperties/OLEPropertiesContainer.cs

Pulling in a couple of minor changes from my other PRs - I don't think these would be counted as API changes as they're private anyway, but that can be confirmed by others.
I don't think these should be settable - ContainerType is set on consturction and I don't think you'd want to change that afterwards, and I don't think there is a need for the context to be replaced - the properties inside it can be changed if needed

Remove a couple of private property setters in OLEPropertiesContainer

---

sources/Test/OpenMcdf.Test/CompoundFileTest.cs

GUIDs are value types and cannot be null

Fix TEST_PR_13 correctness

---

sources/OpenMcdf/CFStorage.cs
sources/OpenMcdf/CompoundFile.cs

Ensure both the root and left sibilings are considered when checking for duplicate SIDs.
Also, remove redundant lookups.

Fix and simplify DirectoryEntry validation

---

sources/OpenMcdf/CFStorage.cs
sources/OpenMcdf/RBTree/RBTreeEnumerator.cs

Improves performance and reduces memory usage

Use Stack for VisitEntries and enumerating RBTree

---

sources/OpenMcdf.Extensions/StreamDecorator.cs
sources/OpenMcdf/CompoundFile.cs
sources/OpenMcdf/DirectoryEntry.cs
sources/OpenMcdf/IDirectoryEntry.cs
sources/OpenMcdf/StreamRW.cs
sources/OpenMcdf/StreamView.cs

- Add/fixes various argument validation for StreamView/StreamDecorator
- Validate reads in StreamRW
- Use StreamRW to validate FAT sector chain reads
- Share StreamRW instances between DirectoryEntry reads/writes

Improve stream read validation

---

.editorconfig
sources/OpenMcdf/CompoundFile.cs
sources/OpenMcdf/StreamView.cs
sources/Test/OpenMcdf.Extensions.Test/OLEPropertiesExtensionsTest.cs
sources/Test/OpenMcdf.Test/CompoundFileTest.cs

Fix Size calculations
Fix Stream Size validations

Fix #184 Fix Size calculations Fix Stream Size validations

---

sources/OpenMcdf.Extensions/StreamDecorator.cs
sources/OpenMcdf/StreamView.cs

Setting the position past the length is expected to increase the length of the stream.

Fix StreamView Position property

---

sources/OpenMcdf.Extensions/StreamDecorator.cs

Visual Studio points out that the parameter name is the second parameter to ArgumentException

Correct the parameters to ArgumentException in StreamDecorator.Seek

---

sources/OpenMcdf.Extensions/OLEProperties/OLEPropertiesContainer.cs
sources/Test/OpenMcdf.Extensions.Test/OLEPropertiesExtensionsTest.cs

Refs comments in https://github.com/ironfede/openmcdf/issues/104 - I think it'd be useful to have a built in function that handles the management of property identifiers and names so that users don't have to do it manually.
Question: The names of user defined properties are required to be unique within a file so it needs some validation.
Should an attempt to add a user defined property with a name that already exists be an error (e.g. throw an exception), or should it replace any existing property with a new one (it might have to handle the new property having a different type than the existing one, which would need to remove the existing property and create a new one)

Add a helper function to add user defined properties to the user defined properties container.

---

sources/OpenMcdf/StreamView.cs

As https://github.com/ironfede/openmcdf/pull/193 but in StreamView - I missed this one previously.

Fix ArgumentException parameter order in StreamView.Seek

---

sources/OpenMcdf.Extensions/OLEProperties/PropertyFactory.cs

The code analysis in Rider pointed out that VT_I8_Property was never used, but as VT_I8 is listed as a permitted property type in https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-oleps/2a4589eb-9a23-4a8b-adbd-3e368233c099 I think it should be plugged in?

Plug VT_I8_Property into PropertyFactory

---

sources/OpenMcdf/StreamView.cs

I tried running the code through the whole solution code analysis in Rider and it determined that 'freeSectors' isn't mutated after creation, so I wonder if it's needed? (StreamView is an internal class, so if there are internal users then there shouldn't be any users at all).
As an extra test, I tried running a benchmark against the current code and with freeSectors removed and got
before:
```
| Method                  | Job      | Runtime  | Mean      | Error     | StdDev     | Median    | Gen0     | Gen1    | Allocated |
|------------------------ |--------- |--------- |----------:|----------:|-----------:|----------:|---------:|--------:|----------:|
| CreateCompoundDocument  | .NET 6.0 | .NET 6.0 |  50.47 us |  1.820 us |   5.251 us |  48.50 us |   6.8359 |  0.1221 |  42.19 KB |
| …
```

Is StreamView::freeSectors needed?

---

OpenMcdf.Ole.Tests/OlePropertiesExtensionsTests.cs
OpenMcdf.Ole/PropertySetNames.cs
StructuredStorageExplorer/MainForm.cs

We have a set of 'well known' guids in ```FormatIdentifiers``` so how about adding the matching property stream names as built in properties?
These are taken from the  FMTID/name table at https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-oleps/e5484a83-3cc1-43a6-afcf-6558059fe36e

[RFC] Add some definitions of known property set names

---

OpenMcdf.Ole/OpenMcdf.Ole.csproj
OpenMcdf/OpenMcdf.csproj

Should enable the trimming and AOT code analyzers so we get warnings if any incompatible features creep in

Mark the .NET 8 versions of the libraries as Trim and AOT compatible

---

.github/workflows/dotnet-desktop.yml

Idea being to enable deterministic build in the CI (so it gets deterministic paths in the debug symbols and such.

Set ContinuousIntegrationBuild to true in CI builds

---

OpenMcdf.Ole/OlePropertiesContainer.cs

The way the code was set up *should* mean that PropertyNames is never null in UserDefinedProperties containers, so it should never be null when it gets to the ```PropertyNames.Any```. However, the compiler can't tell that, so you get nullability warnings in the build
It might be safe to ```!``` the references here, but then - I don't think there should be any problem with just creating PropertyNames here so maybe that's the safer approach to take.

Make sure PropertyNames is always populated in AddUserDefinedProperty()

---

OpenMcdf.Ole.Tests/OlePropertiesExtensionsTests.cs
OpenMcdf.Ole/OlePropertiesContainer.cs

As #142 but against v3.0 and with an extension to one of the unit tests to test that it retains the fmtid for a file with an 'app specific' (i.e not a known value) value,

Rework the handling of FMTID0 in OlePropertiesContainer

---

OpenMcdf.Perf/OpenMcdf.Perf.csproj
OpenMcdf.Perf/Program.cs

Add large write perf methods

---

OpenMcdf/FatStream.cs
OpenMcdf/MiniFatStream.cs

I thought this had already been done :-(

Fix parameter order for ArgumentException

---

OpenMcdf.Ole/DictionaryProperty.cs

I believe this isn't needed after #124, where the read side was changes to remove all the null terminators, and the write side of various other string properties was changed to always write null terminators

Simplify null terminator handling in DictionaryProperty.Write

---

OpenMcdf.Ole/DictionaryProperty.cs
OpenMcdf.Ole/IProperty.cs
OpenMcdf.Ole/ITypedPropertyValue.cs

As discussed elsewhere - IProperty is basically an implementation detail of the property factory machinery so I think it can all be made internal

Make IProperty and related internal

---

OpenMcdf.Ole/PropertyIdentifierAndOffset.cs

I think it should be treated as an implementation detail of the (already internal) PropertySet/PropertySetStream

Make PropertyIdentifierAndOffset internal

---

OpenMcdf.Tests/BinaryReaderTests.cs
OpenMcdf/CfbBinaryReader.cs
OpenMcdf/DifatSectorEnumerator.cs
OpenMcdf/DirectoryEntries.cs
OpenMcdf/DirectoryEntry.cs
OpenMcdf/DirectoryTree.cs
OpenMcdf/Fat.cs
OpenMcdf/FatStream.cs
OpenMcdf/FileFormatException.cs
OpenMcdf/Header.cs
OpenMcdf/MiniFat.cs
OpenMcdf/MiniFatChainEnumerator.cs
OpenMcdf/MiniFatStream.cs
StructuredStorageExplorer/MainForm.cs

Security and validation

---

OpenMcdf.Ole/IBinarySerializable.cs

The previous visibiity changes should have made all usages internal

Make IBinarySerializable internal

---

OpenMcdf.Ole/PropertyContext.cs

I don't think there is a need for this to be subclassable - it's part of the public API of OlePropertiesContainer but instances are created internally and the property is read only, so it can't be replaced with a different class by users.

Seal PropertyContext

---

OpenMcdf/FatChainEnumerator.cs
OpenMcdf/MiniFatChainEnumerator.cs
OpenMcdf/System/BitOperations.cs

Use Floyd's algorithm for FAT cycles

---

OpenMcdf.Ole/OlePropertiesContainer.cs

RFC - is it needed?
It gets set in the constructor and then never used, and i don't think there should be anything that uses it after the constructor has completed.

Remove the 'cfStream' member from OlePropertiesContainer

---

OpenMcdf.Ole/OlePropertiesContainer.cs
OpenMcdf.Ole/PropertySet.cs
OpenMcdf.Ole/PropertySetStream.cs
OpenMcdf.Ole/SpecialPropertyIdentifiers.cs

Rather than having the numerical identifiers in multiple places
refs comments in https://github.com/ironfede/openmcdf/pull/259

Start adding some constants for properties that are treated specially

---

OpenMcdf.Ole.Tests/OlePropertiesExtensionsTests.cs
OpenMcdf.Ole/OlePropertiesContainer.cs
OpenMcdf.Ole/PropertySet.cs

…property is present in the file
As long as PropertyContext has a Locale property, I think it should be populated where possible, and as it happens the existing 'Issue134' test file contains a Locale property that can be used for testing.
A thought whilst looking though - the Microsoft docs at https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-oleps/bb452c07-79f7-46e0-bfb7-122c347cc5c8 state that Locale is an optional property, so I wonder if the PropertyContext.Locale property should be nullable rather than being 0 if there is no locale specified?

Read the PropertySet Locale property into the PropertyContext

---

OpenMcdf.Tests/OpenMcdf.Tests.csproj
OpenMcdf.Tests/RootStorageTests.cs
OpenMcdf/RootContext.cs

Limit V3 compound file stream length to 2 GB

---

OpenMcdf.Ole/OlePropertiesContainer.cs

…from the PropertySetStream directly instead of cloning it.
As suggested in comments in https://github.com/ironfede/openmcdf/pull/259

Use the stream PropertyContext when constructing an OlePropertiesContainer

---

Directory.csproj.props
OpenMcdf.Tests/RootStorageTests.cs
OpenMcdf/Fat.cs
OpenMcdf/FatEntry.cs
OpenMcdf/FatEnumerator.cs
OpenMcdf/FatStream.cs
OpenMcdf/MiniFat.cs
OpenMcdf/RootContext.cs
OpenMcdf/RootStorage.cs

Handle range lock sector

---

StructuredStorageExplorer/MainForm.cs
StructuredStorageExplorer/StructuredStorageExplorer.csproj
StructuredStorageExplorer/Utils.cs
StructuredStorageExplorer/app.manifest

1. Supports displaying special control characters in **StructuredStorageExplorer**. When view the office files encrypted by RMS, there will be control characters such as `\u0006` `\u0009`. Reference [2.1.7.3 Data Spaces Storage (\006DataSpaces)](https://learn.microsoft.com/zh-cn/openspecs/office_file_formats/ms-xls/2d2a5085-fa01-4807-b232-f39878b399ce)
2. Support dpiAware

Enhanced StructuredStorageExplorer Display

---

OpenMcdf/OpenMcdf.csproj

I'd been looking at this wondering if it's be possible to use PolySharp as a dependency free polyfill for the index/range stuff and the local definitions of both IsExternalInit and the various nullability attributes, but then I noticed that it still builds and passes the tests when the package is just removed.
Also, ILSpy doesn't show any dependency on it in the published dll:
So - is it still needed?

Remove unsed IndexRange PacakgeReference

---

OpenMcdf/CfbBinaryReader.cs
OpenMcdf/StreamId.cs

Wine creates storage entries with invalid IDs

Relax start sector ID validation
